# Generated by Django 5.2.6 on 2025-10-26 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('categoria', models.CharField(choices=[('SALARIO', 'Salario'), ('MATERIAL', 'Materiales de Construcción'), ('TRANSPORTE', 'Transporte y Combustible'), ('MAQUINARIA', 'Mantenimiento de Maquinaria'), ('ADMIN', 'Gastos Administrativos'), ('OTRO', 'Otro Gasto')], default='OTRO', max_length=50)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_proyecto', models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
    ]
