# Generated by Django 5.2.6 on 2025-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuánto cuesta adquirir este producto.', max_digits=10),
        ),
    ]
