# Generated by Django 5.2.6 on 2025-10-26 22:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_proyecto', models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario_por_dia', models.DecimalField(decimal_places=2, default=0, help_text='Salario a pagar por día trabajado', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tipo_proyecto', models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.trabajador')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('trabajador', 'fecha', 'tipo_proyecto')},
            },
        ),
    ]
