# Generated by Django 5.2.6 on 2025-11-10 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
