# Generated by Django 5.2.6 on 2025-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ordencompra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='costo_unitario_en_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total_utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
