# Generated by Django 5.2.6 on 2025-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detalleorden_costo_unitario_en_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ABONADA', 'Abonada'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
