# Generated by Django 5.2.6 on 2025-09-10 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('categoria', models.CharField(choices=[('SALARIO', 'Salarios y Honorarios'), ('MATERIAL', 'Materiales y Suministros'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Internet)'), ('TRANSPORTE', 'Transporte y Combustible'), ('MAQUINARIA', 'Mantenimiento de Maquinaria'), ('ADMIN', 'Gastos Administrativos'), ('OTRO', 'Otros Gastos')], max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
