# Generated by Django 5.2.6 on 2025-09-12 21:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gasto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_salida',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='tipo_proyecto',
            field=models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='pago_por_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_proyecto',
            field=models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('SALARIO', 'Salarios y Honorarios'), ('MATERIAL', 'Materiales y Suministros'), ('SERVICIOS', 'Servicios Públicos (Agua, Luz, Internet)'), ('TRANSPORTE', 'Transporte y Combustible'), ('MAQUINARIA', 'Mantenimiento de Maquinaria'), ('ADMIN', 'Gastos Administrativos'), ('OTRO', 'Otro Gasto')], default='OTRO', max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('tipo_proyecto', models.CharField(choices=[('CONSTRUCTORA', 'Constructora'), ('BLOQUERA', 'Bloquera')], default='CONSTRUCTORA', max_length=20)),
                ('registrado_como_gasto', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
        ),
    ]
