# Generated by Django 5.2.6 on 2025-09-16 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_gasto_options_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='pago_por_dia',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('SALARIO', 'Salario'), ('MATERIAL', 'Materiales de Construcción'), ('TRANSPORTE', 'Transporte y Combustible'), ('MAQUINARIA', 'Mantenimiento de Maquinaria'), ('ADMIN', 'Gastos Administrativos'), ('OTRO', 'Otro Gasto')], default='OTRO', max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('trabajador', 'fecha', 'tipo_proyecto')},
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
