# Generated by Django 5.2.6 on 2025-10-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_asistencia_options_alter_trabajador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
