# Generated by Django 5.2.6 on 2025-10-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trabajador_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
