# Generated by Django 5.2.6 on 2025-10-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_ordencompra_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero_venta',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
