# Generated by Django 5.2.6 on 2025-10-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='salario_por_dia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salario a pagar por día trabajado', max_digits=10),
        ),
    ]
